"""auto update

Revision ID: 467980df475b
Revises: 4a79c3434fbc
Create Date: 2026-05-05 07:07:25.699735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467980df475b'
down_revision: Union[str, Sequence[str], None] = '4a79c3434fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_content', 'content_key',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_content', 'content_key',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'default'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###