"""auto update

Revision ID: 57c60ab029ca
Revises: 7ba2dcca103b
Create Date: 2026-05-05 09:23:42.399729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c60ab029ca'
down_revision: Union[str, Sequence[str], None] = '7ba2dcca103b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site_content', 'content_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('site_content_content_key_key'), 'site_content', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('site_content_content_key_key'), 'site_content', ['content_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('site_content', 'content_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###